# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f77ac9407841061ba51d7d6cea2d27022eac9cf70caafbcd06490503232bcd839ea4fd1b07794e3e4331fa4c51a74477a21bec536e800af5ecaac39dbf8de4e2

test:
  secret_key_base: 6f0d130abd9cc9d813bcd570e2b3f587910a356fc6e95155ea819e04f6a8fad33eec3ee763968090f1faa3bccb110360fea4fe8ca580b98208128a206663839b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
